# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-30 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_directmessage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EolMessageConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mail', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
