# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-04 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eol_directmessage', '0002_eolmessageconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EolMessageUserConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50)),
                ('is_muted', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eolmessageuserconfiguration',
            unique_together=set([('user', 'course_id')]),
        ),
        migrations.AlterIndexTogether(
            name='eolmessageuserconfiguration',
            index_together=set([('user', 'course_id')]),
        ),
    ]
