# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-08 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_directmessage', '0003_auto_20200304_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='EolMessageFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50)),
                ('only_staff', models.BooleanField()),
            ],
        ),
    ]
